<?php
/**
 * Created by PhpStorm.
 * User: n3vrax
 * Date: 6/29/2016
 * Time: 7:38 PM
 */

namespace N3vrax\DkUser;

class DkUser
{
    const MESSAGE_CONFIRM_ACCOUNT_MISSING_PARAMS = 1;
    const MESSAGE_CONFIRM_ACCOUNT_INVALID_EMAIL = 2;
    const MESSAGE_CONFIRM_ACCOUNT_INVALID_TOKEN = 3;
    const MESSAGE_CONFIRM_ACCOUNT_DISABLED = 4;
    const MESSAGE_CONFIRM_ACCOUNT_ERROR = 5;
    const MESSAGE_CONFIRM_ACCOUNT_SUCCESS = 6;
    const MESSAGE_CONFIRM_ACCOUNT_INVALID_ACCOUNT = 7;

    const MESSAGE_RESET_PASSWORD_INVALID_EMAIL = 8;
    const MESSAGE_RESET_PASSWORD_INVALID_TOKEN = 9;
    const MESSAGE_RESET_PASSWORD_TOKEN_EXPIRED = 10;
    const MESSAGE_RESET_PASSWORD_MISSING_PARAMS = 11;
    const MESSAGE_RESET_PASSWORD_DISABLED = 12;
    const MESSAGE_RESET_PASSWORD_ERROR = 13;
    const MESSAGE_RESET_PASSWORD_SUCCESS = 14;

    const MESSAGE_FORGOT_PASSWORD_MISSING_EMAIL = 15;
    const MESSAGE_FORGOT_PASSWORD_ERROR = 16;
    const MESSAGE_FORGOT_PASSWORD_SUCCESS = 17;
    
    const MESSAGE_REGISTER_EMPTY_EMAIL = 18;
    const MESSAGE_REGISTER_INVALID_EMAIL = 19;
    const MESSAGE_REGISTER_EMAIL_ALREADY_REGISTERED = 20;
    const MESSAGE_REGISTER_EMPTY_USERNAME = 21;
    const MESSAGE_REGISTER_USERNAME_TOO_SHORT = 22;
    const MESSAGE_REGISTER_USERNAME_INVALID_CHARACTERS = 23;
    const MESSAGE_REGISTER_USERNAME_ALREADY_REGISTERED = 24;
    const MESSAGE_REGISTER_EMPTY_PASSWORD = 25;
    const MESSAGE_REGISTER_PASSWORD_TOO_SHORT = 26;
    const MESSAGE_REGISTER_EMPTY_PASSWORD_CONFIRM = 27;
    const MESSAGE_REGISTER_PASSWORD_CONFIRM_NOT_MATCH = 28;

    const MESSAGE_LOGIN_EMPTY_IDENTITY = 29;
    const MESSAGE_LOGIN_EMPTY_PASSWORD = 30;
    const MESSAGE_LOGIN_PASSWORD_TOO_SHORT = 31;

}