<?php
/**
 * Created by PhpStorm.
 * User: n3vrax
 * Date: 6/29/2016
 * Time: 7:38 PM
 */

namespace N3vrax\DkUser;

class DkUser
{
    const MESSAGE_CONFIRM_ACCOUNT_MISSING_PARAMS = 1;
    const MESSAGE_CONFIRM_ACCOUNT_INVALID_EMAIL = 2;
    const MESSAGE_CONFIRM_ACCOUNT_INVALID_TOKEN = 3;
    const MESSAGE_CONFIRM_ACCOUNT_DISABLED = 4;
    const MESSAGE_CONFIRM_ACCOUNT_ERROR = 5;
    const MESSAGE_CONFIRM_ACCOUNT_SUCCESS = 6;
    const MESSAGE_CONFIRM_ACCOUNT_INVALID_ACCOUNT = 7;

    const MESSAGE_RESET_PASSWORD_INVALID_EMAIL = 8;
    const MESSAGE_RESET_PASSWORD_INVALID_TOKEN = 9;
    const MESSAGE_RESET_PASSWORD_TOKEN_EXPIRED = 10;
    const MESSAGE_RESET_PASSWORD_MISSING_PARAMS = 11;
    const MESSAGE_RESET_PASSWORD_DISABLED = 12;
    const MESSAGE_RESET_PASSWORD_ERROR = 13;
    const MESSAGE_RESET_PASSWORD_SUCCESS = 14;

    const MESSAGE_FORGOT_PASSWORD_MISSING_EMAIL = 15;
    const MESSAGE_FORGOT_PASSWORD_ERROR = 16;
    const MESSAGE_FORGOT_PASSWORD_SUCCESS = 17;
}